implemented fetcher
Tridentinus/Team-Project-461 pull request #18
Opened 2024-09-06 21:01 UTC by Tridentinus

2024-09-06 21:11 UTC, rtjord commented on .gitignore
node_modules/ is already at the top of the .gitignore. Does this do something different?

2024-09-06 21:12 UTC, rtjord commented on src/graphqlClient.js
Did you mean to include this file?

2024-09-06 21:13 UTC, rtjord commented on src/main.js
Did you mean to include this file? Also, which TypeScript file was used to generate this?

2024-09-06 21:14 UTC, rtjord commented on src/myLog.log
I think we should add log files to the .gitignore

2024-09-06 21:18 UTC, rtjord requested changes
I don't think we should include JS files and log files in our commits. When you build the project, you can tell it to put the build files in the dist/ directory, which is not tracked by git. Also, we should add log files to the gitignore.

2024-09-07 00:08 UTC, Tridentinus commented on src/myLog.log
ok sure

2024-09-07 00:09 UTC, Tridentinus commented on .gitignore
no clue I added it to bottom because I wanted to be safe

2024-09-07 01:03 UTC, Tridentinus reviewed
sounds good

2024-09-07 01:03 UTC, Tridentinus commented
ok I made

2024-09-07 02:13 UTC, rtjord approved these changes

2024-09-07 02:13 UTC, merged